.editorconfig
ctco-dev/inner-source_kotlin_spark_template pull request #47
Opened 2018-07-28 10:00 UTC by viktor-yengovatov

* code formatting

2018-07-28 16:44 UTC, sa1nt requested changes
I'd suggest we limit this file to: 
* use 4 spaces indentation for `[*]` (the default)
* override for `[*.sql]` to have 2 spaces
* override for `[*.sh]` to have 2 spaces and `LF` line breaks

2018-07-30 06:33 UTC, antonsjevtusenko commented on .editorconfig
> +[*.java]
Do we need lines 6-8?

2018-07-30 08:46 UTC, viktor-yengovatov commented on .editorconfig
> +[*.java]
removed

2018-07-30 09:02 UTC, antonsjevtusenko approved these changes

2018-07-30 09:57 UTC, sa1nt approved these changes

2018-07-31 12:10 UTC, merged